/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-10-08 08:52:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Digital Library - Login</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);\n");
      out.write("            min-height: 100vh;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-container {\n");
      out.write("            display: flex;\n");
      out.write("            width: 90%;\n");
      out.write("            max-width: 1000px;\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.1);\n");
      out.write("            border-radius: 15px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            background: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-image {\n");
      out.write("            width: 40%;\n");
      out.write("            /* ✅ YOUR PINTEREST IMAGE URL */\n");
      out.write("            background: url('https://i.pinimg.com/564x/40/cc/22/40cc229415acfff1801b8c9dc2015c77.jpg') no-repeat center center;\n");
      out.write("            background-size: cover;\n");
      out.write("            position: relative;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .quote-box {\n");
      out.write("            background: rgba(255,255,255,0.85);\n");
      out.write("            padding: 30px;\n");
      out.write("            border-radius: 15px;\n");
      out.write("            text-align: center;\n");
      out.write("            max-width: 80%;\n");
      out.write("            backdrop-filter: blur(10px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .quote-text {\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            font-style: italic;\n");
      out.write("            color: #333;\n");
      out.write("            line-height: 1.6;\n");
      out.write("            font-family: 'Georgia', serif;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-form {\n");
      out.write("            width: 60%;\n");
      out.write("            padding: 40px;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-title {\n");
      out.write("            font-size: 2rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #333;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-label {\n");
      out.write("            font-weight: 500;\n");
      out.write("            color: #555;\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control {\n");
      out.write("            padding: 12px;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            transition: border-color 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus {\n");
      out.write("            border-color: #0d6efd;\n");
      out.write("            box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-login {\n");
      out.write("            background: #0d6efd;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            padding: 12px 20px;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background 0.3s ease;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-login:hover {\n");
      out.write("            background: #0b5ed7;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-link {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 20px;\n");
      out.write("            color: #666;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-link a {\n");
      out.write("            color: #0d6efd;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-link a:hover {\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Corner Icons */\n");
      out.write("        .top-left, .top-right {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 20px;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            color: #666;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-left {\n");
      out.write("            left: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-right {\n");
      out.write("            right: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive */\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .login-container {\n");
      out.write("                flex-direction: column;\n");
      out.write("                width: 95%;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .login-image {\n");
      out.write("                width: 100%;\n");
      out.write("                height: 200px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .login-form {\n");
      out.write("                width: 100%;\n");
      out.write("                padding: 30px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .login-title {\n");
      out.write("                font-size: 1.5rem;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Corner Icons -->\n");
      out.write("    <div class=\"top-left\">📚</div>\n");
      out.write("    <div class=\"top-right\">📖</div>\n");
      out.write("\n");
      out.write("    <div class=\"login-container\">\n");
      out.write("        <!-- Left Side: Your Pinterest Book Image + Quote -->\n");
      out.write("        <div class=\"login-image\">\n");
      out.write("            <div class=\"quote-box\">\n");
      out.write("                <div class=\"quote-text\">\n");
      out.write("                    \"Books are a uniquely portable magic.\"\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Right Side: Login Form -->\n");
      out.write("        <div class=\"login-form\">\n");
      out.write("            <h2 class=\"login-title\">Digital Library - Login</h2>\n");
      out.write("            \n");
      out.write("            ");

                String error = (String) request.getAttribute("error");
                if (error != null) {
                    out.println("<div class='alert alert-danger'>" + error + "</div>");
                }
            
      out.write("\n");
      out.write("\n");
      out.write("            <form method=\"post\" action=\"LoginServlet\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"username\" class=\"form-label\">Username</label>\n");
      out.write("                    <input type=\"text\" id=\"username\" name=\"username\" class=\"form-control\" required>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"password\" class=\"form-label\">Password</label>\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" required>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"btn-login\">Login</button>\n");
      out.write("            </form>\n");
      out.write("            \n");
      out.write("            <div class=\"register-link\">\n");
      out.write("                Don't have an account? <a href=\"register.jsp\">Register here</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Bottom Icon -->\n");
      out.write("    <div style=\"position: fixed; bottom: 20px; right: 20px; font-size: 1.5rem; color: #666;\">👓</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
